---
general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $GAMMAPY_DATA/cta-1dc/index/gps
    filters:
        - filter_type: ids
          obs_ids: [110380, 111140, 111159]

datasets:
    dataset-type: MapDataset
    stack-datasets: true
    offset-max: 2.5 deg
    psf-kernel-radius: 0.3 deg
    geom:
        skydir: [0, 0]
        width: [10, 8]
        binsz: 0.02
        coordsys: GAL
        proj: CAR
        axes:
            - name: energy
              hi_bnd: 10
              lo_bnd: 0.1
              nbin: 10
              interp: log
              node_type: edges
              unit: TeV

fit: {}

detection:
    threshold: 15
    map: sqrt_ts


